/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSchedulesRouteImport } from './routes/dashboard/schedules'
import { Route as DashboardPayrollsRouteImport } from './routes/dashboard/payrolls'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard/messages'
import { Route as DashboardIncidentsRouteImport } from './routes/dashboard/incidents'
import { Route as DashboardAttendanceRouteImport } from './routes/dashboard/attendance'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as DashboardSitesIndexRouteImport } from './routes/dashboard/sites/index'
import { Route as DashboardEmployeesIndexRouteImport } from './routes/dashboard/employees/index'
import { Route as DashboardCompaniesIndexRouteImport } from './routes/dashboard/companies/index'
import { Route as DashboardSitesSiteIdRouteImport } from './routes/dashboard/sites/$siteId'
import { Route as DashboardEmployeesIdRouteImport } from './routes/dashboard/employees/$Id'
import { Route as DashboardCompaniesIdRouteImport } from './routes/dashboard/companies/$Id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardSitesEditSiteIdRouteImport } from './routes/dashboard/sites/edit/$siteId'
import { Route as DashboardEmployeesEditEmployeeIdRouteImport } from './routes/dashboard/employees/edit/$employeeId'
import { Route as DashboardCompaniesEditCompanyIdRouteImport } from './routes/dashboard/companies/edit/$companyId'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSchedulesRoute = DashboardSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPayrollsRoute = DashboardPayrollsRouteImport.update({
  id: '/payrolls',
  path: '/payrolls',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardIncidentsRoute = DashboardIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAttendanceRoute = DashboardAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSitesIndexRoute = DashboardSitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEmployeesIndexRoute = DashboardEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCompaniesIndexRoute = DashboardCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSitesSiteIdRoute = DashboardSitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEmployeesIdRoute = DashboardEmployeesIdRouteImport.update({
  id: '/employees/$Id',
  path: '/employees/$Id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCompaniesIdRoute = DashboardCompaniesIdRouteImport.update({
  id: '/companies/$Id',
  path: '/companies/$Id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSitesEditSiteIdRoute =
  DashboardSitesEditSiteIdRouteImport.update({
    id: '/sites/edit/$siteId',
    path: '/sites/edit/$siteId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEmployeesEditEmployeeIdRoute =
  DashboardEmployeesEditEmployeeIdRouteImport.update({
    id: '/employees/edit/$employeeId',
    path: '/employees/edit/$employeeId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCompaniesEditCompanyIdRoute =
  DashboardCompaniesEditCompanyIdRouteImport.update({
    id: '/companies/edit/$companyId',
    path: '/companies/edit/$companyId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/incidents': typeof DashboardIncidentsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/payrolls': typeof DashboardPayrollsRoute
  '/dashboard/schedules': typeof DashboardSchedulesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/companies/$Id': typeof DashboardCompaniesIdRoute
  '/dashboard/employees/$Id': typeof DashboardEmployeesIdRoute
  '/dashboard/sites/$siteId': typeof DashboardSitesSiteIdRoute
  '/dashboard/companies': typeof DashboardCompaniesIndexRoute
  '/dashboard/employees': typeof DashboardEmployeesIndexRoute
  '/dashboard/sites': typeof DashboardSitesIndexRoute
  '/dashboard/companies/edit/$companyId': typeof DashboardCompaniesEditCompanyIdRoute
  '/dashboard/employees/edit/$employeeId': typeof DashboardEmployeesEditEmployeeIdRoute
  '/dashboard/sites/edit/$siteId': typeof DashboardSitesEditSiteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/incidents': typeof DashboardIncidentsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/payrolls': typeof DashboardPayrollsRoute
  '/dashboard/schedules': typeof DashboardSchedulesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/companies/$Id': typeof DashboardCompaniesIdRoute
  '/dashboard/employees/$Id': typeof DashboardEmployeesIdRoute
  '/dashboard/sites/$siteId': typeof DashboardSitesSiteIdRoute
  '/dashboard/companies': typeof DashboardCompaniesIndexRoute
  '/dashboard/employees': typeof DashboardEmployeesIndexRoute
  '/dashboard/sites': typeof DashboardSitesIndexRoute
  '/dashboard/companies/edit/$companyId': typeof DashboardCompaniesEditCompanyIdRoute
  '/dashboard/employees/edit/$employeeId': typeof DashboardEmployeesEditEmployeeIdRoute
  '/dashboard/sites/edit/$siteId': typeof DashboardSitesEditSiteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/incidents': typeof DashboardIncidentsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/payrolls': typeof DashboardPayrollsRoute
  '/dashboard/schedules': typeof DashboardSchedulesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/companies/$Id': typeof DashboardCompaniesIdRoute
  '/dashboard/employees/$Id': typeof DashboardEmployeesIdRoute
  '/dashboard/sites/$siteId': typeof DashboardSitesSiteIdRoute
  '/dashboard/companies/': typeof DashboardCompaniesIndexRoute
  '/dashboard/employees/': typeof DashboardEmployeesIndexRoute
  '/dashboard/sites/': typeof DashboardSitesIndexRoute
  '/dashboard/companies/edit/$companyId': typeof DashboardCompaniesEditCompanyIdRoute
  '/dashboard/employees/edit/$employeeId': typeof DashboardEmployeesEditEmployeeIdRoute
  '/dashboard/sites/edit/$siteId': typeof DashboardSitesEditSiteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/attendance'
    | '/dashboard/incidents'
    | '/dashboard/messages'
    | '/dashboard/payrolls'
    | '/dashboard/schedules'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/companies/$Id'
    | '/dashboard/employees/$Id'
    | '/dashboard/sites/$siteId'
    | '/dashboard/companies'
    | '/dashboard/employees'
    | '/dashboard/sites'
    | '/dashboard/companies/edit/$companyId'
    | '/dashboard/employees/edit/$employeeId'
    | '/dashboard/sites/edit/$siteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/attendance'
    | '/dashboard/incidents'
    | '/dashboard/messages'
    | '/dashboard/payrolls'
    | '/dashboard/schedules'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/companies/$Id'
    | '/dashboard/employees/$Id'
    | '/dashboard/sites/$siteId'
    | '/dashboard/companies'
    | '/dashboard/employees'
    | '/dashboard/sites'
    | '/dashboard/companies/edit/$companyId'
    | '/dashboard/employees/edit/$employeeId'
    | '/dashboard/sites/edit/$siteId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/dashboard/attendance'
    | '/dashboard/incidents'
    | '/dashboard/messages'
    | '/dashboard/payrolls'
    | '/dashboard/schedules'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/companies/$Id'
    | '/dashboard/employees/$Id'
    | '/dashboard/sites/$siteId'
    | '/dashboard/companies/'
    | '/dashboard/employees/'
    | '/dashboard/sites/'
    | '/dashboard/companies/edit/$companyId'
    | '/dashboard/employees/edit/$employeeId'
    | '/dashboard/sites/edit/$siteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/schedules': {
      id: '/dashboard/schedules'
      path: '/schedules'
      fullPath: '/dashboard/schedules'
      preLoaderRoute: typeof DashboardSchedulesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/payrolls': {
      id: '/dashboard/payrolls'
      path: '/payrolls'
      fullPath: '/dashboard/payrolls'
      preLoaderRoute: typeof DashboardPayrollsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/incidents': {
      id: '/dashboard/incidents'
      path: '/incidents'
      fullPath: '/dashboard/incidents'
      preLoaderRoute: typeof DashboardIncidentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/attendance': {
      id: '/dashboard/attendance'
      path: '/attendance'
      fullPath: '/dashboard/attendance'
      preLoaderRoute: typeof DashboardAttendanceRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sites/': {
      id: '/dashboard/sites/'
      path: '/sites'
      fullPath: '/dashboard/sites'
      preLoaderRoute: typeof DashboardSitesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/employees/': {
      id: '/dashboard/employees/'
      path: '/employees'
      fullPath: '/dashboard/employees'
      preLoaderRoute: typeof DashboardEmployeesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/companies/': {
      id: '/dashboard/companies/'
      path: '/companies'
      fullPath: '/dashboard/companies'
      preLoaderRoute: typeof DashboardCompaniesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/sites/$siteId': {
      id: '/dashboard/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/dashboard/sites/$siteId'
      preLoaderRoute: typeof DashboardSitesSiteIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/employees/$Id': {
      id: '/dashboard/employees/$Id'
      path: '/employees/$Id'
      fullPath: '/dashboard/employees/$Id'
      preLoaderRoute: typeof DashboardEmployeesIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/companies/$Id': {
      id: '/dashboard/companies/$Id'
      path: '/companies/$Id'
      fullPath: '/dashboard/companies/$Id'
      preLoaderRoute: typeof DashboardCompaniesIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sites/edit/$siteId': {
      id: '/dashboard/sites/edit/$siteId'
      path: '/sites/edit/$siteId'
      fullPath: '/dashboard/sites/edit/$siteId'
      preLoaderRoute: typeof DashboardSitesEditSiteIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/employees/edit/$employeeId': {
      id: '/dashboard/employees/edit/$employeeId'
      path: '/employees/edit/$employeeId'
      fullPath: '/dashboard/employees/edit/$employeeId'
      preLoaderRoute: typeof DashboardEmployeesEditEmployeeIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/companies/edit/$companyId': {
      id: '/dashboard/companies/edit/$companyId'
      path: '/companies/edit/$companyId'
      fullPath: '/dashboard/companies/edit/$companyId'
      preLoaderRoute: typeof DashboardCompaniesEditCompanyIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAttendanceRoute: typeof DashboardAttendanceRoute
  DashboardIncidentsRoute: typeof DashboardIncidentsRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardPayrollsRoute: typeof DashboardPayrollsRoute
  DashboardSchedulesRoute: typeof DashboardSchedulesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCompaniesIdRoute: typeof DashboardCompaniesIdRoute
  DashboardEmployeesIdRoute: typeof DashboardEmployeesIdRoute
  DashboardSitesSiteIdRoute: typeof DashboardSitesSiteIdRoute
  DashboardCompaniesIndexRoute: typeof DashboardCompaniesIndexRoute
  DashboardEmployeesIndexRoute: typeof DashboardEmployeesIndexRoute
  DashboardSitesIndexRoute: typeof DashboardSitesIndexRoute
  DashboardCompaniesEditCompanyIdRoute: typeof DashboardCompaniesEditCompanyIdRoute
  DashboardEmployeesEditEmployeeIdRoute: typeof DashboardEmployeesEditEmployeeIdRoute
  DashboardSitesEditSiteIdRoute: typeof DashboardSitesEditSiteIdRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAttendanceRoute: DashboardAttendanceRoute,
  DashboardIncidentsRoute: DashboardIncidentsRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardPayrollsRoute: DashboardPayrollsRoute,
  DashboardSchedulesRoute: DashboardSchedulesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCompaniesIdRoute: DashboardCompaniesIdRoute,
  DashboardEmployeesIdRoute: DashboardEmployeesIdRoute,
  DashboardSitesSiteIdRoute: DashboardSitesSiteIdRoute,
  DashboardCompaniesIndexRoute: DashboardCompaniesIndexRoute,
  DashboardEmployeesIndexRoute: DashboardEmployeesIndexRoute,
  DashboardSitesIndexRoute: DashboardSitesIndexRoute,
  DashboardCompaniesEditCompanyIdRoute: DashboardCompaniesEditCompanyIdRoute,
  DashboardEmployeesEditEmployeeIdRoute: DashboardEmployeesEditEmployeeIdRoute,
  DashboardSitesEditSiteIdRoute: DashboardSitesEditSiteIdRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
